import type { SiteBlueprint, MediaPlan } from "../types";
import { buildWxrXml, type WxrItem, type WxrPostMeta, type WxrCategory } from "../templates/wxr-boilerplate";
import { IdManager } from "../id-manager";

/**
 * Generates all WXR XML files from a blueprint.
 *
 * Returns a map of path → XML string:
 *   "page/page" → pages WXR
 *   "post/post" → blog posts WXR
 *   "nav_menu_item/nav_menu_item" → nav items WXR
 *   "[cpt]/[cpt]" → custom post type WXR
 *
 * Blog post content:encoded HTML is passed in as pre-generated by LLM.
 * Everything else is deterministic.
 */

interface WxrGenOptions {
  blueprint: SiteBlueprint;
  idMgr: IdManager;
  /**
   * IDs of pages whose Elementor JSON generated successfully. WXR page records
   * and nav menu items are filtered to this set so we never ship orphan WP
   * records pointing at missing Elementor content (which would render as blank
   * theme pages).
   */
  generatedPageIds: Set<string>;
  /** Pre-generated HTML content for blog posts, keyed by post slug */
  postContent?: Record<string, string>;
  /** Media (logo + brand assets) to emit as wp:attachment items. */
  mediaPlan?: MediaPlan;
}

export interface WxrGenResult {
  files: Record<string, string>;
  /** Nav menu item IDs keyed by page title */
  navMenuItemIds: Record<string, number>;
  /** All content items by post type for manifest wp-content section */
  wpContentItems: Record<string, { id: number; title: string }[]>;
}

export function generateWxrFiles(options: WxrGenOptions): WxrGenResult {
  const { blueprint, idMgr, generatedPageIds, postContent = {}, mediaPlan } = options;
  const files: Record<string, string> = {};
  const navMenuItemIds: Record<string, number> = {};
  const wpContentItems: Record<string, { id: number; title: string }[]> = {};

  const wxrAuthor = {
    login: blueprint.author.login,
    email: blueprint.author.email,
    displayName: blueprint.author.name,
  };

  // Only emit WP records for pages whose Elementor JSON generated. Pages that
  // failed are excluded everywhere — WXR items, manifest's wp-content.page,
  // and the nav menu — so a partial-success kit doesn't ship orphan WP posts
  // that WordPress would render as blank theme pages.
  const successfulPages = blueprint.pages.filter((page) =>
    generatedPageIds.has(String(page.id))
  );

  // ── Pages WXR ──────────────────────────────────────────────────

  const pageItems: WxrItem[] = successfulPages.map((page) => ({
    postId: page.id,
    title: page.title,
    slug: page.slug,
    postType: "page",
    status: "publish",
    content: "",
    postMeta: [
      { key: "_elementor_edit_mode", value: "builder" },
      { key: "_elementor_template_type", value: "wp-page" },
      { key: "_wp_page_template", value: "elementor_header_footer" },
    ],
  }));

  files["page/page"] = buildWxrXml({
    siteName: blueprint.name,
    siteUrl: blueprint.siteUrl,
    author: wxrAuthor,
    items: pageItems,
  });

  // Track page items for manifest wp-content
  wpContentItems["page"] = pageItems.map((p) => ({ id: p.postId, title: p.title }));

  // ── Blog Posts WXR ─────────────────────────────────────────────

  if (blueprint.hasBlog && blueprint.posts.length > 0) {
    const blogCategories: WxrCategory[] = blueprint.categories
      .filter((c) => c.taxonomy === "category")
      .map((c) => ({
        termId: c.termId,
        slug: c.slug,
        name: c.name,
        taxonomy: "category",
      }));

    const postItems: WxrItem[] = blueprint.posts.map((post) => {
      const content = postContent[post.slug] || `<p>${post.excerpt}</p>`;

      // Find matching category
      const cat = blueprint.categories.find(
        (c) => c.slug === post.category && c.taxonomy === "category"
      );

      return {
        postId: post.id,
        title: post.title,
        slug: post.slug,
        postType: "post",
        status: "publish",
        content,
        excerpt: post.excerpt,
        categories: cat
          ? [{ domain: "category", slug: cat.slug, name: cat.name }]
          : [],
        postMeta: [
          { key: "_elementor_edit_mode", value: "builder" },
          { key: "_elementor_template_type", value: "wp-post" },
          { key: "_elementor_version", value: "3.35.7" },
          { key: "_elementor_pro_version", value: "3.35.7" },
        ],
      };
    });

    files["post/post"] = buildWxrXml({
      siteName: blueprint.name,
      siteUrl: blueprint.siteUrl,
      author: wxrAuthor,
      items: postItems,
      categories: blogCategories,
    });

    // Track post items for manifest wp-content
    wpContentItems["post"] = postItems.map((p) => ({ id: p.postId, title: p.title }));
  }

  // ── Nav Menu Items WXR ─────────────────────────────────────────

  const navItems: WxrItem[] = successfulPages.map((page, index) => {
    const navItemId = idMgr.allocatePostId();
    navMenuItemIds[page.title] = navItemId;
    return {
      postId: navItemId,
      title: page.title,
      slug: page.title.toLowerCase().replace(/\s+/g, "-"),
      postType: "nav_menu_item",
      status: "publish",
      menuOrder: index + 1,
      postMeta: [
        { key: "_menu_item_type", value: "post_type" },
        { key: "_menu_item_menu_item_parent", value: "0" },
        { key: "_menu_item_object_id", value: String(page.id) },
        { key: "_menu_item_object", value: "page" },
        { key: "_menu_item_target", value: "" },
        { key: "_menu_item_classes", value: "a:1:{i:0;s:0:\"\";}" },
        { key: "_menu_item_xfn", value: "" },
        { key: "_menu_item_url", value: "" },
      ],
      categories: [
        { domain: "nav_menu", slug: "main-menu", name: "Main Menu" },
      ],
    };
  });

  files["nav_menu_item/nav_menu_item"] = buildWxrXml({
    siteName: blueprint.name,
    siteUrl: blueprint.siteUrl,
    author: wxrAuthor,
    items: navItems,
  });

  // Track nav menu items for manifest wp-content
  wpContentItems["nav_menu_item"] = navItems.map((n) => ({
    id: n.postId,
    title: n.title,
  }));

  // ── Brand media attachments ────────────────────────────────────
  //
  // Brand-asset images (logo, photos, icons) ride in their own WXR file as
  // attachment posts. WordPress imports each as a media-library entry; the
  // companion file copies live under wp-content/uploads/<YYYY>/<MM>/.

  if (mediaPlan && mediaPlan.attachments.length > 0) {
    const attachItems: WxrItem[] = mediaPlan.attachments.map((a) => ({
      postId: a.id,
      title: a.title,
      slug: a.slug,
      postType: "attachment",
      status: "inherit",
      attachmentUrl: a.url,
      postMeta: [
        // _wp_attached_file is what WP looks up to find the file on disk.
        { key: "_wp_attached_file", value: a.zipPath.replace(/^wp-content\/uploads\//, "") },
        // Minimal _wp_attachment_metadata — width/height optional for SVG.
        {
          key: "_wp_attachment_metadata",
          value: `a:5:{s:5:"width";i:${a.width};s:6:"height";i:${a.height};s:4:"file";s:${a.zipPath.replace(/^wp-content\/uploads\//, "").length}:"${a.zipPath.replace(/^wp-content\/uploads\//, "")}";s:5:"sizes";a:0:{}s:10:"image_meta";a:0:{}}`,
        },
      ],
    }));

    files["attachment/attachment"] = buildWxrXml({
      siteName: blueprint.name,
      siteUrl: blueprint.siteUrl,
      author: wxrAuthor,
      items: attachItems,
    });

    wpContentItems["attachment"] = attachItems.map((a) => ({
      id: a.postId,
      title: a.title,
    }));
  }

  // ── CPT WXR Files ──────────────────────────────────────────────

  for (const cpt of blueprint.customPostTypes) {
    // Build taxonomy categories for this CPT
    const cptCategories: WxrCategory[] = blueprint.categories
      .filter((c) => c.taxonomy === cpt.name)
      .map((c) => ({
        termId: c.termId,
        slug: c.slug,
        name: c.name,
        taxonomy: cpt.name,
      }));

    const cptItems: WxrItem[] = [];

    for (const post of cpt.posts) {
      // Build post meta from ACF fields
      const postMeta: WxrPostMeta[] = [
        { key: "_elementor_edit_mode", value: "builder" },
      ];

      // Add ACF field pairs: fieldname (value) + _fieldname (field key)
      for (const field of cpt.fields) {
        const value = post.fields[field.key] || "";
        postMeta.push({ key: field.key, value });
        postMeta.push({ key: `_${field.key}`, value: field.fieldId });
      }

      // Add thumbnail (placeholder attachment)
      if (post.thumbnailId) {
        postMeta.push({
          key: "_thumbnail_id",
          value: String(post.thumbnailId),
        });

        // Also add the attachment item
        cptItems.push({
          postId: post.thumbnailId,
          title: `${post.title} Featured Image`,
          slug: `${post.slug}-featured-image`,
          postType: "attachment",
          status: "inherit",
          parentId: post.id,
          attachmentUrl: `https://placehold.co/1200x800/png?text=${encodeURIComponent(post.title)}`,
          postMeta: [
            {
              key: "_wp_attachment_metadata",
              value: `a:5:{s:5:"width";i:1200;s:6:"height";i:800;s:4:"file";s:20:"${post.slug}.png";s:5:"sizes";a:0:{}s:10:"image_meta";a:0:{}}`,
            },
          ],
        });
      }

      cptItems.push({
        postId: post.id,
        title: post.title,
        slug: post.slug,
        postType: cpt.name,
        status: "publish",
        content: "",
        postMeta,
      });
    }

    files[`${cpt.name}/${cpt.name}`] = buildWxrXml({
      siteName: blueprint.name,
      siteUrl: blueprint.siteUrl,
      author: wxrAuthor,
      items: cptItems,
      categories: cptCategories,
    });

    // Track CPT items for manifest wp-content
    wpContentItems[cpt.name] = cptItems
      .filter((i) => i.postType !== "attachment")
      .map((i) => ({ id: i.postId, title: i.title }));
  }

  return { files, navMenuItemIds, wpContentItems };
}
